[tools]
chezmoi = "latest"
bat = "latest"
ripgrep = "latest"
lsd = "latest"
fzf = "latest"
fd = "latest"
neovim = "latest"
node = "latest"
python = "latest"
# usage = "latest"   # for mise completion
